security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  providers:
    users_in_memory: { memory: null }
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      entry_point: App\Security\UsersAuthenticator
      custom_authenticator: App\Security\UsersAuthenticator # Corrigez l'indentation ici
      # form_login:
      #   login_path: app_login
      #   check_path: app_login
      logout:
        path: app_logout
      # remember_me:
      #   secret: "%kernel.secret%"
      #   lifetime: 604800
      #   path: /
      #   always_remember_me: true
  access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/, roles: ROLE_USER }
    # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
