vich_uploader:
  db_driver: orm

  mappings:
    products:
      uri_prefix: /images/vehicule
      upload_destination: "%kernel.project_dir%/public/images/vehicule"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
